import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ApiError, createWoodshedApi, operationId, type Ballot, type DiscoveredEvent, type WoodshedApi } from "./api.ts";

export type Candidate = { id:string; title:string; detail:string };
class BallotConflictError extends Error { readonly ballot?:Ballot;constructor(ballot?:Ballot){super("ballot-conflict");this.ballot=ballot} }
const INITIAL: Candidate[] = [
  {id:"song_alpha",title:"North Star",detail:"Key: C · Readiness unknown"},
  {id:"song_bravo",title:"Open Road",detail:"Key: G · Ready for rehearsal"},
  {id:"song_charlie",title:"Quiet River",detail:"Key: D · Arrangement pending"},
];
export function RankedBallot({initial=INITIAL,revision,onSave}:{initial?:Candidate[];revision?:number;onSave?:(rankings:string[],expectedRevision:number,operationId:string)=>Promise<number>}) {
  const [songs,setSongs]=useState(initial); const [selected,setSelected]=useState(initial[0]?.id); const [announcement,setAnnouncement]=useState(""); const [saveState,setSaveState]=useState(onSave?`Saved · revision ${revision??0}`:"Demo data"); const [saving,setSaving]=useState(false); const buttons=useRef(new Map<string,HTMLButtonElement>()); const retry=useRef<{payload:string;operationId:string}|null>(null);
  function move(index:number,delta:number){if(saving)return;const next=index+delta;if(next<0||next>=songs.length)return;const copy=[...songs];const [item]=copy.splice(index,1);if(!item)return;copy.splice(next,0,item);setSongs(copy);setSelected(item.id);setSaveState(onSave?"Unsaved changes":"Unsaved demo changes");setAnnouncement(`${item.title} moved to position ${next+1} of ${copy.length}`);requestAnimationFrame(()=>buttons.current.get(item.id)?.focus());}
  async function save(){if(saving)return;if(!onSave){setSaveState("Demo saved in this tab");setAnnouncement("Demo ballot saved in this tab. It will reset on refresh.");return;}const rankings=songs.map(song=>song.id);const payload=JSON.stringify({rankings,revision:revision??0});const retained=retry.current?.payload===payload?retry.current:{payload,operationId:operationId("ballot")};retry.current=retained;setSaving(true);setSaveState("Saving…");try{const next=await onSave(rankings,revision??0,retained.operationId);retry.current=null;setSaveState(`Ballot saved · revision ${next}`);setAnnouncement(`Ballot saved at revision ${next}.`)}catch(error){if(error instanceof BallotConflictError){retry.current=null;if(error.ballot){const refreshed=error.ballot.candidates.map(candidate=>({...candidate,detail:"Eligible for this event"}));setSongs(refreshed);setSelected(refreshed[0]?.id);setSaveState(`Ballot changed elsewhere · refreshed to revision ${error.ballot.revision}`);setAnnouncement(`Another tab changed this ballot. Refreshed to revision ${error.ballot.revision}.`)}else{setSaveState("Ballot changed elsewhere · refresh needed");setAnnouncement("Another tab changed this ballot, but the latest ballot could not be loaded. Refresh before saving again.")}}else{setSaveState("Save failed · try again");setAnnouncement("Ballot could not be saved. Your order remains on this screen.")}}finally{setSaving(false)}}
  return <section aria-labelledby="ballot-heading" className="panel">
    <div className="section-heading"><div><span className="eyebrow">Your ballot</span><h2 id="ballot-heading">Rank the songs you want to hear</h2></div><span className="save-state">{saveState}</span></div>
    <p className="hint">Your order is private. Use the buttons or keyboard to change it; number 1 is your top choice.</p><p className="sr-only" aria-live="polite">{announcement}</p>
    <ol className="rank-list">{songs.map((song,index)=><li key={song.id} className={selected===song.id?"song-card selected":"song-card"}>
      <span className="rank" aria-hidden="true">{index+1}</span><button ref={node=>{if(node)buttons.current.set(song.id,node);else buttons.current.delete(song.id)}} className="song-select" onClick={()=>setSelected(song.id)} aria-pressed={selected===song.id}><strong>{song.title}</strong><span>{song.detail}</span></button>
      <div className="move-actions" role="group" aria-label={`Move ${song.title}`}><button onClick={()=>move(index,-1)} disabled={saving||index===0} aria-label={`Move ${song.title} up`}>↑</button><button onClick={()=>move(index,1)} disabled={saving||index===songs.length-1} aria-label={`Move ${song.title} down`}>↓</button></div>
      {selected===song.id&&<div className="selected-context"><span>Selected song</span><dl><div><dt>Ballot position</dt><dd>{index+1} of {songs.length}</dd></div><div><dt>Availability</dt><dd>Eligible for this event</dd></div></dl></div>}
    </li>)}</ol><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?"Saving ballot…":"Save ranked ballot"}</button>
  </section>;
}

export function ProposalForm({onSubmit}:{onSubmit?:(title:string,operationId:string)=>Promise<"submitted"|"eligible">}){const [title,setTitle]=useState("");const [message,setMessage]=useState("");const [sending,setSending]=useState(false);const retry=useRef<{title:string;operationId:string}|null>(null);async function submit(clean:string){if(sending)return;if(!onSubmit){setMessage(`${clean} submission simulated. Nothing was queued or sent.`);setTitle("");return;}const retained=retry.current?.title===clean?retry.current:{title:clean,operationId:operationId("proposal")};retry.current=retained;setSending(true);setMessage("Sending proposal…");try{const state=await onSubmit(clean,retained.operationId);retry.current=null;setMessage(state==="eligible"?`${clean} accepted by this event’s immediate proposal policy.`:`${clean} sent for organizer review.`);setTitle("")}catch{setMessage("Proposal was not sent. Please try again.")}finally{setSending(false)}}return <section className="panel"><span className="eyebrow">Not on the list?</span><h2>Propose a song</h2><form onSubmit={event=>{event.preventDefault();const clean=title.trim();if(clean)void submit(clean)}}><label htmlFor="proposal">Song title</label><div className="inline"><input id="proposal" required placeholder="Enter a song title" value={title} onChange={event=>setTitle(event.target.value)} disabled={sending}/><button className="secondary" disabled={sending}>{sending?"Sending…":"Send for consideration"}</button></div><p className="hint">Depending on this event’s policy, proposals enter voting immediately or wait for organizer review.</p><p className="coordination-status" role="status" aria-live="polite">{message}</p></form></section>}

const ARRANGEMENTS=[
  {id:"arrangement_north",title:"North Star",key:"C",revision:2,parts:[{id:"lead",name:"Lead vocal",performer:"Avery",state:"Volunteer",readiness:"Learning"},{id:"drums",name:"Drums",performer:"Jordan",state:"Assigned",readiness:"Rehearsal-ready"}]},
  {id:"arrangement_road",title:"Open Road",key:"G",revision:1,parts:[{id:"lead",name:"Lead vocal",performer:"Avery",state:"Volunteer",readiness:"Interested"},{id:"guitar",name:"Lead guitar",performer:"Morgan",state:"Backup accepted",readiness:"Learning"}]},
] as const;

export function RehearsalWorkspace(){
  const [selected,setSelected]=useState<(typeof ARRANGEMENTS)[number]["id"]>(ARRANGEMENTS[0].id);const [message,setMessage]=useState("");const [offered,setOffered]=useState(false);const current=ARRANGEMENTS.find(item=>item.id===selected)??ARRANGEMENTS[0];
  return <section className="panel coordination" aria-labelledby="staffing-heading"><div className="section-heading"><div><span className="eyebrow">Staff & rehearse</span><h2 id="staffing-heading">Prepare the selected repertoire</h2></div><span className="save-state">Provider-independent</span></div><p className="hint">Volunteer interest stays separate from confirmed assignments. Arrangement changes only reset the readiness they affect.</p>
    <div className="coordination-layout"><div className="arrangement-list" role="group" aria-label="Event arrangements">{ARRANGEMENTS.map(item=><button key={item.id} aria-label={`${item.title} arrangement`} aria-pressed={selected===item.id} className={selected===item.id?"arrangement-card selected":"arrangement-card"} onClick={()=>{setSelected(item.id);setMessage(`${item.title} selected`);setOffered(false)}}><strong>{item.title}</strong><span>Key {item.key} · {item.parts.length} parts</span></button>)}</div>
      <article className="arrangement-focus" aria-labelledby="selected-arrangement"><span className="eyebrow">Selected arrangement</span><h3 id="selected-arrangement">{current.title}</h3><dl className="attribute-strip"><div><dt>Key</dt><dd>{current.key}</dd></div><div><dt>Decision</dt><dd>Version {current.revision}</dd></div><div><dt>Required parts</dt><dd>{current.parts.length}</dd></div></dl>
        <ul className="part-list">{current.parts.map(part=><li key={part.id}><div><strong>{part.name}</strong><span>{part.performer} · {part.state}</span></div><span className="readiness">{part.readiness}</span>{part.id==="lead"&&!offered?<button onClick={()=>{setOffered(true);setMessage(`Offer sent to ${part.performer}`)}} aria-label={`Offer ${part.name.toLowerCase()} to ${part.performer}`}>Send offer</button>:part.id==="lead"?<button onClick={()=>setMessage(`${part.name} marked rehearsal-ready`)} aria-label={`Mark ${part.name.toLowerCase()} rehearsal-ready`}>Mark ready</button>:null}</li>)}</ul>
      </article></div><p role="status" aria-live="polite" className="coordination-status">{message}</p>
    <details><summary>Schedule a rehearsal</summary><fieldset><legend>Candidate windows</legend><label><input type="radio" name="slot"/> Sunday, 1:30 AM (before clock change)</label><label><input type="radio" name="slot"/> Sunday, 2:00 AM (after clock change)</label></fieldset><button className="primary" onClick={()=>setMessage("Rehearsal publish simulated. No calendar update was sent.")}>Publish rehearsal</button></details>
  </section>;
}

const LIVE_QUEUE=[{id:"live_north",title:"North Star",detail:"Key C",state:"current"},{id:"live_road",title:"Open Road",detail:"Key G",state:"queued"},{id:"live_river",title:"Quiet River",detail:"Key D",state:"queued"}] as const;
export function LiveWorkspace({initialOffline=false}:{initialOffline?:boolean}){const [current,setCurrent]=useState<(typeof LIVE_QUEUE)[number]["id"]>(LIVE_QUEUE[0].id);const [message,setMessage]=useState("");const [history,setHistory]=useState<string[]>([]);const [handoff,setHandoff]=useState<"none"|"pending">("none");const [offline,setOffline]=useState(initialOffline||(typeof navigator!=="undefined"&&!navigator.onLine));const currentSong=LIVE_QUEUE.find(item=>item.id===current)??LIVE_QUEUE[0];const currentPerformed=history.includes(currentSong.id);const currentHeading=useRef<HTMLHeadingElement>(null);useEffect(()=>{const online=()=>setOffline(initialOffline);const disconnected=()=>setOffline(true);globalThis.addEventListener("online",online);globalThis.addEventListener("offline",disconnected);return()=>{globalThis.removeEventListener("online",online);globalThis.removeEventListener("offline",disconnected)}},[initialOffline]);function makeCurrent(item:(typeof LIVE_QUEUE)[number]){setCurrent(item.id);setMessage(`${item.title} is now current`);requestAnimationFrame(()=>currentHeading.current?.focus());}
  return <section className="panel live-workspace" aria-labelledby="live-heading"><div className="section-heading"><div><span className="eyebrow">Live performance</span><h2 id="live-heading">Stage lead</h2></div><span className={offline?"sync-state offline":"sync-state"}>{offline?"Simulated offline state":"Demo connection available"}</span></div><div className="freshness"><strong>{offline?"Connection unavailable":"Demo state only"}</strong><span>{offline?"Example authority epoch 3 · changes stay only in this demo until reconnection":"This prototype does not send stage-lead changes to the API"}</span></div><p role="status" aria-live="polite" className="coordination-status">{message}</p>
    <article className="current-song" aria-labelledby="current-song"><span>Current song</span><h3 id="current-song" ref={currentHeading} tabIndex={-1}>{currentSong.title}</h3><p>{currentSong.detail} · visible to the audience</p><div className="live-actions"><button disabled={currentPerformed} onClick={()=>{setHistory(old=>[...old,currentSong.id]);setMessage(`${currentSong.title} marked performed`)}}>Mark performed</button><button onClick={()=>setMessage(`${currentSong.title} deferred; sync pending`)}>Defer</button></div></article>
    <div className="live-grid"><section aria-labelledby="queue-heading"><h3 id="queue-heading">Up next</h3><ol className="live-queue">{LIVE_QUEUE.filter(item=>item.id!==current).map(item=><li key={item.id}><div><strong>{item.title}</strong><span>{item.detail} · queued</span></div><button onClick={()=>makeCurrent(item)} aria-label={`Make ${item.title} current`}>Make current</button></li>)}</ol></section><section aria-labelledby="suggestion-heading"><h3 id="suggestion-heading">Audience suggestions</h3><div className="suggestion"><strong>Golden Hour</strong><span>Suggested next · awaiting stage lead</span><button onClick={()=>setMessage("Golden Hour added to the queue")}>Add to queue</button></div></section></div>
    <details open={handoff==="pending"}><summary>Authority & device</summary><p>This example illustrates single-device stage authority; no device is server-confirmed.</p>{handoff==="none"?<button aria-label="Hand off stage lead" onClick={()=>{setHandoff("pending");setMessage("Handoff simulation opened; no server request was sent")}}>Hand off stage lead</button>:<div className="handoff"><strong>Simulated handoff pending</strong><span>The example recipient would not become authoritative until a real server confirmed it.</span><button onClick={()=>{setHandoff("none");setMessage("Handoff simulation cancelled")}}>Cancel handoff</button></div>} <button className="danger" onClick={()=>setMessage("Clear-device action simulated; no persistent event data exists")}>Clear this device</button></details>
    <details><summary>Performance history</summary>{history.length?<ol>{history.map(id=><li key={id}>{LIVE_QUEUE.find(item=>item.id===id)?.title??id}</li>)}</ol>:<p>No completed songs yet.</p>}</details></section>;
}

const eventStatus=(state:string)=>state==="voting"?"Voting open":state.charAt(0).toUpperCase()+state.slice(1);
const candidateDetail=()=>"Eligible for this event";
const DEFAULT_API = createWoodshedApi();

export function App({api=DEFAULT_API}:{api?:WoodshedApi}){const [events,setEvents]=useState<DiscoveredEvent[]>([]);const [eventId,setEventId]=useState("");const [ballotState,setBallotState]=useState<{eventId:string;ballot:Ballot}|null>(null);const [assurance,setAssurance]=useState<"loading"|"open-public"|"invite-confirmed"|"invite-required"|"empty"|"error">("loading");const selectedEvent=events.find(({id})=>id===eventId)??events[0];const ballot=selectedEvent&&ballotState?.eventId===selectedEvent.id?ballotState.ballot:null;const selectionGeneration=useRef(0);
  useEffect(()=>{selectionGeneration.current+=1},[selectedEvent?.id]);
  useEffect(()=>{let active=true;const load=async()=>{try{const result=await api.discover();const pathEventId=globalThis.location?.pathname.match(/^\/events\/([^/]+)/)?.[1];let available=result.events;if(pathEventId&&!available.some(event=>event.id===pathEventId)){try{const invited=(await api.eventContext(pathEventId)).event;available=[...available,invited]}catch(error){if(!(error instanceof ApiError)||![401,403,404].includes(error.status))throw error}}if(!active)return;setEvents(available);setEventId(old=>old||(pathEventId&&available.some(event=>event.id===pathEventId)?pathEventId:available[0]?.id)||"");if(available.length===0)setAssurance("empty")}catch{if(active)setAssurance("error")}};void load();return()=>{active=false}},[api]);
  useEffect(()=>{if(!selectedEvent)return;const loadingEventId=selectedEvent.id;let active=true;setAssurance("loading");const load=async()=>{try{let loaded:Ballot;try{loaded=await api.ballot(loadingEventId)}catch(error){if(!(error instanceof ApiError)||![401,403].includes(error.status))throw error;if(selectedEvent.participationPolicy!=="open"){if(active)setAssurance("invite-required");return;}await api.joinOpen(loadingEventId);loaded=await api.ballot(loadingEventId)}if(active){setBallotState({eventId:loadingEventId,ballot:loaded});setAssurance(selectedEvent.participationPolicy==="open"?"open-public":"invite-confirmed")}}catch{if(active)setAssurance("error")}};void load();return()=>{active=false}},[api,selectedEvent]);
  const saveBallot=useCallback(async(rankings:string[],expectedRevision:number,requestOperationId:string)=>{if(!selectedEvent)throw new Error("event unavailable");const submittedEventId=selectedEvent.id;const submittedGeneration=selectionGeneration.current;try{const saved=await api.saveBallot(submittedEventId,{expectedRevision,rankings,operationId:requestOperationId});if(selectionGeneration.current===submittedGeneration)setBallotState(current=>current?.eventId===submittedEventId?{eventId:submittedEventId,ballot:{...current.ballot,revision:saved.revision,candidates:rankings.map(id=>current.ballot.candidates.find(candidate=>candidate.id===id)).filter((candidate):candidate is Ballot["candidates"][number]=>Boolean(candidate))}}:current);return saved.revision}catch(error){if(!(error instanceof ApiError)||error.status!==409)throw error;if(selectionGeneration.current!==submittedGeneration)throw new BallotConflictError();let latest:Ballot|undefined;try{latest=await api.ballot(submittedEventId);if(selectionGeneration.current===submittedGeneration)setBallotState(current=>current?.eventId===submittedEventId?{eventId:submittedEventId,ballot:latest!}:current)}catch{/* The conflict is definitive even when reconciliation cannot load. */}throw new BallotConflictError(latest)}},[api,selectedEvent]);
  const propose=useCallback(async(title:string,requestOperationId:string)=>{if(!selectedEvent)throw new Error("event unavailable");return (await api.propose(selectedEvent.id,{title,operationId:requestOperationId})).state},[api,selectedEvent]);
  const ballotCandidates=useMemo(()=>ballot?.candidates.map(candidate=>({...candidate,detail:candidateDetail()}))??[],[ballot?.candidates]);
  return <div className="app-shell"><header><a className="brand" href="/">Woodshed <small>River City Music Circle</small></a><nav aria-label="Community"><a href="#events" aria-current="page">Events</a><a href="#library">Shared library</a></nav></header><div className="demo-notice" role="note"><strong>Connected participant preview</strong><span>Discovery, joining, ballots, and proposals use the local API. Rehearsal and live controls remain clearly labeled simulations.</span></div><main>
  <aside id="events" aria-labelledby="events-heading"><span className="eyebrow">Community workspace</span><h1 id="events-heading">Events</h1>{events.length?<><label htmlFor="event-switcher">Current event</label><select id="event-switcher" value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(event=><option key={event.id} value={event.id}>{event.name}</option>)}</select><div className="event-list">{events.map(event=><button key={event.id} className={eventId===event.id?"event-card selected":"event-card"} onClick={()=>setEventId(event.id)}><strong>{event.name}</strong><span>{eventStatus(event.state)} · {event.visibility}</span></button>)}</div></>:<p>{assurance==="error"?"Events unavailable":assurance==="empty"?"No events are currently available.":"Loading events…"}</p>}</aside>
  <div className="content">{selectedEvent&&<section className="focus-card" aria-labelledby="selected-event"><div><span className="eyebrow">Selected event</span><h1 id="selected-event">{selectedEvent.name}</h1><p>This event’s choices and attributes are grouped here, distinct from neighboring events.</p></div><dl><div><dt>Status</dt><dd>{eventStatus(selectedEvent.state)}</dd></div><div><dt>Visibility</dt><dd>{selectedEvent.visibility}</dd></div><div><dt>Entry</dt><dd>{selectedEvent.participationPolicy==="open"?"Open":"Invite required"}</dd></div></dl></section>}{assurance==="error"?<div className="assurance error" role="alert"><strong>Participant services are unavailable</strong><span>Check the local API and retry by refreshing this page. No changes were saved.</span></div>:assurance==="empty"?<div className="assurance" role="status"><strong>No events available</strong><span>There are no published events to join right now.</span></div>:<div className="assurance" role="status"><strong>{assurance==="open-public"?"Open public participation":assurance==="invite-confirmed"?"Invite confirmed":assurance==="invite-required"?"Invite required":"Connecting participant session…"}</strong><span>{assurance==="open-public"?"A scoped accountless session is active for this event.":assurance==="invite-confirmed"?"Your invite session is active for this event.":assurance==="invite-required"?"Open this event through an organizer-provided invite link.":"Loading the event’s participation state."}</span></div>}{ballot&&<><RankedBallot key={`ballot:${selectedEvent?.id}`} initial={ballotCandidates} revision={ballot.revision} onSave={saveBallot}/><ProposalForm key={`proposal:${selectedEvent?.id}`} onSubmit={propose}/></>}<RehearsalWorkspace/><LiveWorkspace/></div>
  </main></div>}
