import "@testing-library/jest-dom/vitest";
import { act,render,screen,waitFor } from "@testing-library/react";
import { userEvent } from "@testing-library/user-event";
import { describe,expect,it,vi } from "vitest";
import { App, LiveWorkspace, ProposalForm, RankedBallot, RehearsalWorkspace } from "./App.tsx";
import { ApiError, type WoodshedApi } from "./api.ts";

function connectedApi(overrides: Partial<WoodshedApi> = {}): WoodshedApi {
  return {
    discover: async () => ({ events: [{ id: "event_public", name: "Summer Singalong", state: "voting", visibility: "public", participationPolicy: "open" }] }),
    eventContext: async (eventId) => ({ event: { id:eventId,name:"Invited Event",state:"voting",visibility:"unlisted",participationPolicy:"invite" } }),
    joinOpen: async () => ({ assurance: "open-public" }),
    ballot: async () => ({ method: "ranked-choice", revision: 2, candidates: [{ id: "song_alpha", title: "North Star" }, { id: "song_bravo", title: "Open Road" }] }),
    saveBallot: async (_eventId, input) => ({ method: "ranked-choice", revision: input.expectedRevision + 1, rankings: input.rankings }),
    propose: async (_eventId, input) => ({ id: "proposal_demo", title: input.title, state: "submitted" }),
    logout: async () => {},
    ...overrides,
  };
}

describe("ranked ballot accessibility",()=>{
  it("provides keyboard-operable reorder controls, selection context, and focus retention",async()=>{const user=userEvent.setup();render(<RankedBallot/>);const down=screen.getByRole("button",{name:"Move North Star down"});await user.click(down);await waitFor(()=>expect(screen.getByRole("button",{name:/North Star Key:/})).toHaveFocus());expect(screen.getByText("Selected song")).toBeVisible();expect(screen.getByText("North Star moved to position 2 of 3")).toBeInTheDocument();});
  it("labels local demo state and confirms a demo save",async()=>{const user=userEvent.setup();render(<RankedBallot/>);await user.click(screen.getByRole("button",{name:"Move North Star down"}));expect(screen.getByText("Unsaved demo changes")).toBeVisible();await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(screen.getByText("Demo saved in this tab")).toBeVisible();expect(screen.getByText(/reset on refresh/)).toBeInTheDocument();});
  it("keeps one uneditable save in flight and reuses its operation id after an ambiguous failure",async()=>{const user=userEvent.setup();let rejectFirst:((reason?:unknown)=>void)|undefined;const first=new Promise<number>((_resolve,reject)=>{rejectFirst=reject});const save=vi.fn().mockReturnValueOnce(first).mockResolvedValueOnce(1);render(<RankedBallot onSave={save}/>);const button=screen.getByRole("button",{name:"Save ranked ballot"});await user.click(button);expect(screen.getByRole("button",{name:"Saving ballot…"})).toBeDisabled();expect(screen.getByRole("button",{name:"Move North Star down"})).toBeDisabled();await user.click(screen.getByRole("button",{name:"Saving ballot…"}));expect(save).toHaveBeenCalledTimes(1);rejectFirst?.(new Error("response lost"));expect(await screen.findByText("Save failed · try again")).toBeVisible();await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(save).toHaveBeenCalledTimes(2);expect(save.mock.calls[1]?.[2]).toBe(save.mock.calls[0]?.[2]);expect(await screen.findByText("Ballot saved · revision 1")).toBeVisible();});
});

describe("API-backed participant choice",()=>{
  it("reuses a proposal operation id after an ambiguous failure",async()=>{const user=userEvent.setup();const submit=vi.fn().mockRejectedValueOnce(new Error("response lost")).mockResolvedValueOnce("submitted");render(<ProposalForm onSubmit={submit}/>);await user.type(screen.getByRole("textbox",{name:"Song title"}),"Lantern Song");await user.click(screen.getByRole("button",{name:"Send for consideration"}));expect(await screen.findByText("Proposal was not sent. Please try again.")).toBeVisible();await user.click(screen.getByRole("button",{name:"Send for consideration"}));expect(await screen.findByText("Lantern Song sent for organizer review.")).toBeVisible();expect(submit.mock.calls[1]?.[1]).toBe(submit.mock.calls[0]?.[1]);});
  it("joins only after an unauthorized ballot read, then persists ballot and proposal changes",async()=>{const calls:{rankings?:string[];proposal?:string;joins:number;ballots:number}={joins:0,ballots:0};const api=connectedApi({joinOpen:async()=>{calls.joins+=1;return {assurance:"open-public"}},ballot:async()=>{calls.ballots+=1;if(calls.ballots===1)throw new ApiError(401,"unauthorized");return {method:"ranked-choice",revision:2,candidates:[{id:"song_alpha",title:"North Star"},{id:"song_bravo",title:"Open Road"}]}},saveBallot:async(_eventId,input)=>{calls.rankings=input.rankings;return {method:"ranked-choice",revision:input.expectedRevision+1,rankings:input.rankings}},propose:async(_eventId,input)=>{calls.proposal=input.title;return {id:"proposal_demo",title:input.title,state:"submitted"}}});const user=userEvent.setup();render(<App api={api}/>);expect(await screen.findByText("Open public participation")).toBeVisible();expect(calls).toMatchObject({joins:1,ballots:2});expect(await screen.findByRole("button",{name:/Move North Star down/})).toBeEnabled();await user.click(screen.getByRole("button",{name:"Move North Star down"}));await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(await screen.findByText("Ballot saved · revision 3")).toBeVisible();expect(calls.rankings).toEqual(["song_bravo","song_alpha"]);await user.type(screen.getByRole("textbox",{name:"Song title"}),"Lantern Song");await user.click(screen.getByRole("button",{name:"Send for consideration"}));expect(await screen.findByText("Lantern Song sent for organizer review.")).toBeVisible();expect(calls.proposal).toBe("Lantern Song");});
  it("surfaces API failure without falling back to pretend persistence",async()=>{const api=connectedApi({discover:async()=>{throw new Error("offline")}});render(<App api={api}/>);expect(await screen.findByRole("alert")).toHaveTextContent("Participant services are unavailable");expect(screen.queryByText("Example participation state")).not.toBeInTheDocument();});
  it("keeps rehearsal and live actions explicitly synthetic",async()=>{const user=userEvent.setup();render(<App api={connectedApi()}/>);await screen.findByText("Open public participation");await user.click(screen.getByText("Schedule a rehearsal"));await user.click(screen.getByRole("button",{name:"Publish rehearsal"}));expect(screen.getByText(/No calendar update was sent/)).toBeVisible();expect(screen.getByText("Demo connection available")).toBeVisible();});
  it("does not apply a delayed save to a newly selected event",async()=>{let resolveSave:((value:{method:"ranked-choice";revision:number;rankings:string[]})=>void)|undefined;const api=connectedApi({discover:async()=>({events:[{id:"event_a",name:"First Event",state:"voting",visibility:"public",participationPolicy:"open"},{id:"event_b",name:"Second Event",state:"voting",visibility:"public",participationPolicy:"open"}]}),ballot:async eventId=>({method:"ranked-choice",revision:0,candidates:[{id:eventId==="event_a"?"song_alpha":"song_bravo",title:eventId==="event_a"?"North Star":"Open Road"}]}),saveBallot:async()=>new Promise(resolve=>{resolveSave=resolve})});const user=userEvent.setup();render(<App api={api}/>);await screen.findByRole("button",{name:"Save ranked ballot"});await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));await user.selectOptions(screen.getByLabelText("Current event"),"event_b");await screen.findByRole("button",{name:"Save ranked ballot"});resolveSave?.({method:"ranked-choice",revision:1,rankings:["song_alpha"]});await waitFor(()=>expect(screen.getByRole("button",{name:/Open Road Eligible/})).toBeVisible());expect(screen.queryByRole("button",{name:/North Star Eligible/})).not.toBeInTheDocument();});
  it("ignores a delayed save after switching away from and back to the same event",async()=>{let resolveOld:((value:{method:"ranked-choice";revision:number;rankings:string[]})=>void)|undefined;let aReads=0;const revisions:number[]=[];const api=connectedApi({discover:async()=>({events:[{id:"event_a",name:"First Event",state:"voting",visibility:"public",participationPolicy:"open"},{id:"event_b",name:"Second Event",state:"voting",visibility:"public",participationPolicy:"open"}]}),ballot:async eventId=>eventId==="event_b"?{method:"ranked-choice",revision:0,candidates:[{id:"song_bravo",title:"Open Road"}]}:(aReads++===0?{method:"ranked-choice",revision:0,candidates:[{id:"song_alpha",title:"North Star"}]}:{method:"ranked-choice",revision:2,candidates:[{id:"song_charlie",title:"Quiet River"}]}),saveBallot:async(_eventId,input)=>{revisions.push(input.expectedRevision);if(revisions.length===1)return new Promise(resolve=>{resolveOld=resolve});return {method:"ranked-choice",revision:3,rankings:input.rankings}}});const user=userEvent.setup();render(<App api={api}/>);await screen.findByRole("button",{name:/North Star Eligible/});await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));await user.selectOptions(screen.getByLabelText("Current event"),"event_b");await screen.findByRole("button",{name:/Open Road Eligible/});await user.selectOptions(screen.getByLabelText("Current event"),"event_a");await screen.findByRole("button",{name:/Quiet River Eligible/});await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(await screen.findByText("Ballot saved · revision 3")).toBeVisible();resolveOld?.({method:"ranked-choice",revision:1,rankings:["song_alpha"]});await waitFor(()=>expect(screen.getByRole("button",{name:/Quiet River Eligible/})).toBeVisible());expect(revisions).toEqual([0,2]);});
  it("does not carry an in-flight proposal into a newly selected event",async()=>{let resolveProposal:((value:{id:string;title:string;state:"submitted"})=>void)|undefined;const api=connectedApi({discover:async()=>({events:[{id:"event_a",name:"First Event",state:"voting",visibility:"public",participationPolicy:"open"},{id:"event_b",name:"Second Event",state:"voting",visibility:"public",participationPolicy:"open"}]}),ballot:async eventId=>({method:"ranked-choice",revision:0,candidates:[{id:`song_${eventId}`,title:`Song ${eventId}`}]}),propose:async(_eventId,input)=>new Promise(resolve=>{resolveProposal=value=>resolve({...value,title:input.title})})});const user=userEvent.setup();render(<App api={api}/>);const title=await screen.findByRole("textbox",{name:"Song title"});await user.type(title,"Old Event Song");await user.click(screen.getByRole("button",{name:"Send for consideration"}));await user.selectOptions(screen.getByLabelText("Current event"),"event_b");const newTitle=await screen.findByRole("textbox",{name:"Song title"});expect(newTitle).toHaveValue("");resolveProposal?.({id:"proposal_old",title:"Old Event Song",state:"submitted"});await waitFor(()=>expect(screen.queryByText("Old Event Song sent for organizer review.")).not.toBeInTheDocument());});
  it("replaces an event-scoped session when another open event returns forbidden",async()=>{let current="event_a";const joins:string[]=[];const api=connectedApi({discover:async()=>({events:[{id:"event_a",name:"First Event",state:"voting",visibility:"public",participationPolicy:"open"},{id:"event_b",name:"Second Event",state:"voting",visibility:"public",participationPolicy:"open"}]}),ballot:async eventId=>{if(eventId!==current)throw new ApiError(403,"denied");return {method:"ranked-choice",revision:0,candidates:[{id:eventId==="event_a"?"song_alpha":"song_bravo",title:eventId==="event_a"?"North Star":"Open Road"}]};},joinOpen:async eventId=>{current=eventId;joins.push(eventId);return {assurance:"open-public"}}});const user=userEvent.setup();render(<App api={api}/>);await screen.findByRole("button",{name:/North Star Eligible/});await user.selectOptions(screen.getByLabelText("Current event"),"event_b");expect(await screen.findByRole("button",{name:/Open Road Eligible/})).toBeVisible();expect(joins).toEqual(["event_b"]);});
  it("reloads the canonical ballot after a definitive revision conflict",async()=>{let reads=0;const saves:number[]=[];const api=connectedApi({ballot:async()=>{reads+=1;return reads===1?{method:"ranked-choice",revision:2,candidates:[{id:"song_alpha",title:"North Star"},{id:"song_bravo",title:"Open Road"}]}:{method:"ranked-choice",revision:3,candidates:[{id:"song_bravo",title:"Open Road"},{id:"song_alpha",title:"North Star"}]}},saveBallot:async(_eventId,input)=>{saves.push(input.expectedRevision);if(saves.length===1)throw new ApiError(409,"conflict");return {method:"ranked-choice",revision:4,rankings:input.rankings}}});const user=userEvent.setup();render(<App api={api}/>);await screen.findByRole("button",{name:/Move North Star down/});await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(await screen.findByText("Ballot changed elsewhere · refreshed to revision 3")).toBeVisible();expect(screen.getByRole("button",{name:/Open Road Eligible/})).toBeVisible();await user.click(screen.getByRole("button",{name:"Save ranked ballot"}));expect(await screen.findByText("Ballot saved · revision 4")).toBeVisible();expect(saves).toEqual([2,3]);});
  it("selects an invited unlisted event from the redirect path",async()=>{window.history.pushState({},"","/events/event_invited");try{const api=connectedApi({discover:async()=>({events:[{id:"event_public",name:"Public Event",state:"voting",visibility:"public",participationPolicy:"open"}]}),eventContext:async()=>({event:{id:"event_invited",name:"Invited Workshop",state:"voting",visibility:"unlisted",participationPolicy:"invite"}}),ballot:async eventId=>({method:"ranked-choice",revision:0,candidates:[{id:"song_invited",title:`Song for ${eventId}`} ]})});render(<App api={api}/>);expect(await screen.findByRole("heading",{name:"Invited Workshop"})).toBeVisible();expect(await screen.findByText("Invite confirmed")).toBeVisible();expect(screen.getByText("Your invite session is active for this event.")).toBeVisible();expect(await screen.findByRole("button",{name:/Song for event_invited Eligible/})).toBeVisible();}finally{window.history.pushState({},"","/")}});
  it("reports a completed discovery with no available events",async()=>{render(<App api={connectedApi({discover:async()=>({events:[]})})}/>);expect(await screen.findByText("No events are currently available.")).toBeVisible();expect(screen.getByText("No events available")).toBeVisible();expect(screen.queryByText("Loading events…")).not.toBeInTheDocument();});
  it("describes proposal handling truthfully for either organizer policy",async()=>{render(<App api={connectedApi()}/>);expect(await screen.findByText(/proposals enter voting immediately or wait for organizer review/)).toBeVisible();});
});

describe("live stage-lead accessibility",()=>{
  it("makes the current song distinct, retains focus, and announces queue changes",async()=>{const user=userEvent.setup();render(<LiveWorkspace/>);expect(screen.getByText("Current song")).toBeVisible();expect(screen.getByRole("heading",{name:"North Star"})).toBeVisible();await user.click(screen.getByRole("button",{name:"Make Open Road current"}));const heading=screen.getByRole("heading",{name:"Open Road"});expect(heading).toBeVisible();await waitFor(()=>expect(heading).toHaveFocus());expect(screen.getByRole("status")).toHaveTextContent("Open Road is now current");});
  it("does not record a queue move as a completed performance and prevents duplicate perform actions",async()=>{const user=userEvent.setup();render(<LiveWorkspace/>);await user.click(screen.getByText("Performance history"));await user.click(screen.getByRole("button",{name:"Make Open Road current"}));expect(screen.getByText("No completed songs yet.")).toBeVisible();const performed=screen.getByRole("button",{name:"Mark performed"});await user.click(performed);expect(performed).toBeDisabled();});
  it("shows simulated offline authority and handoff state explicitly",()=>{render(<LiveWorkspace initialOffline/>);expect(screen.getByText("Simulated offline state")).toBeVisible();expect(screen.getByText(/example authority epoch/i)).toBeVisible();expect(screen.getByText(/connection unavailable/i)).toBeVisible();expect(screen.getByRole("button",{name:"Hand off stage lead"})).toBeEnabled();});
  it("never claims demo changes reached the server after an offline-to-online transition",async()=>{render(<LiveWorkspace/>);act(()=>window.dispatchEvent(new Event("offline")));expect(screen.getByText("Simulated offline state")).toBeVisible();expect(screen.getByText("Connection unavailable")).toBeVisible();act(()=>window.dispatchEvent(new Event("online")));await waitFor(()=>expect(screen.getByText("Demo state only")).toBeVisible());expect(screen.getByText(/does not send stage-lead changes to the API/)).toBeVisible();expect(screen.queryByText(/everything synced/i)).not.toBeInTheDocument();expect(screen.queryByText(/server confirmed/i)).not.toBeInTheDocument();});
});

describe("rehearsal coordination accessibility",()=>{
  it("keeps selected arrangement context obvious and supports assignment/readiness workflow by keyboard",async()=>{const user=userEvent.setup();render(<RehearsalWorkspace/>);const second=screen.getByRole("button",{name:/Open Road arrangement/});await user.tab();while(document.activeElement!==second)await user.tab();await user.keyboard("{Enter}");expect(screen.getByRole("heading",{name:"Open Road"})).toBeVisible();expect(screen.getByText("Selected arrangement")).toBeVisible();await user.click(screen.getByRole("button",{name:"Offer lead vocal to Avery"}));expect(screen.getByRole("status")).toHaveTextContent("Offer sent to Avery");expect(screen.getByRole("button",{name:"Mark lead vocal rehearsal-ready"})).toBeEnabled();});
});
