import { randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import type { AuthorityCoordinator,AuthorityLease } from "../../application/src/live-coordinator.ts";
type Handoff={token:string;from:string;to:string;epoch:number};
export class SqliteAuthorityCoordinator implements AuthorityCoordinator {
  readonly database:DatabaseSync;constructor(database=new DatabaseSync(":memory:")){this.database=database;this.database.exec("PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS live_authority(event_id TEXT PRIMARY KEY,device_installation_id TEXT NOT NULL,epoch INTEGER NOT NULL CHECK(epoch>0),confirmed_at TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN(0,1))) STRICT; CREATE TABLE IF NOT EXISTS live_handoffs(event_id TEXT PRIMARY KEY,token TEXT NOT NULL,from_device TEXT NOT NULL,to_device TEXT NOT NULL,authority_epoch INTEGER NOT NULL) STRICT;");}
  private transaction<T>(body:()=>T){this.database.exec("BEGIN IMMEDIATE");try{const value=body();this.database.exec("COMMIT");return value;}catch(error){this.database.exec("ROLLBACK");throw error;}}
  current(eventId:string){const row=this.database.prepare("SELECT event_id,device_installation_id,epoch,confirmed_at,revoked FROM live_authority WHERE event_id=? AND revoked=0").get(eventId) as {event_id:string;device_installation_id:string;epoch:number;confirmed_at:string;revoked:number}|undefined;return row?{eventId:row.event_id,deviceInstallationId:row.device_installation_id,epoch:row.epoch,confirmedAt:row.confirmed_at,revoked:false}:null;}
  acquire(eventId:string,device:string){return this.transaction(()=>{const old=this.database.prepare("SELECT epoch,revoked FROM live_authority WHERE event_id=?").get(eventId) as {epoch:number;revoked:number}|undefined;if(old&&!old.revoked)throw new Error("authority-already-held");const epoch=(old?.epoch??0)+1,confirmedAt=new Date().toISOString();this.database.prepare("INSERT INTO live_authority(event_id,device_installation_id,epoch,confirmed_at,revoked) VALUES(?,?,?,?,0) ON CONFLICT(event_id) DO UPDATE SET device_installation_id=excluded.device_installation_id,epoch=excluded.epoch,confirmed_at=excluded.confirmed_at,revoked=0").run(eventId,device,epoch,confirmedAt);return {eventId,deviceInstallationId:device,epoch,confirmedAt,revoked:false};});}
  requestHandoff(eventId:string,from:string,to:string){const lease=this.current(eventId);if(!lease||lease.deviceInstallationId!==from||from===to)throw new Error("handoff-denied");const value={token:randomUUID(),from,to,epoch:lease.epoch};this.database.prepare("INSERT INTO live_handoffs(event_id,token,from_device,to_device,authority_epoch) VALUES(?,?,?,?,?) ON CONFLICT(event_id) DO UPDATE SET token=excluded.token,from_device=excluded.from_device,to_device=excluded.to_device,authority_epoch=excluded.authority_epoch").run(eventId,value.token,from,to,value.epoch);return value;}
  private handoff(eventId:string){return this.database.prepare("SELECT token,from_device AS 'from',to_device AS 'to',authority_epoch AS epoch FROM live_handoffs WHERE event_id=?").get(eventId) as Handoff|undefined;}
  confirmHandoff(eventId:string,token:string,device:string){return this.transaction(()=>{const handoff=this.handoff(eventId),lease=this.current(eventId);if(!handoff||handoff.token!==token||handoff.to!==device||lease?.epoch!==handoff.epoch)throw new Error("handoff-denied");const epoch=lease.epoch+1,confirmedAt=new Date().toISOString();this.database.prepare("UPDATE live_authority SET device_installation_id=?,epoch=?,confirmed_at=? WHERE event_id=? AND epoch=?").run(device,epoch,confirmedAt,eventId,lease.epoch);this.database.prepare("DELETE FROM live_handoffs WHERE event_id=?").run(eventId);return {eventId,deviceInstallationId:device,epoch,confirmedAt,revoked:false};});}
  cancelHandoff(eventId:string,token:string,device:string){const value=this.handoff(eventId);if(!value||value.token!==token||value.from!==device)throw new Error("handoff-denied");this.database.prepare("DELETE FROM live_handoffs WHERE event_id=?").run(eventId);}
  revokeAndRecover(eventId:string,lost:string,recovery:string){return this.transaction(()=>{const lease=this.current(eventId);if(!lease||lease.deviceInstallationId!==lost)throw new Error("recovery-denied");const epoch=lease.epoch+1,confirmedAt=new Date().toISOString();this.database.prepare("UPDATE live_authority SET device_installation_id=?,epoch=?,confirmed_at=? WHERE event_id=? AND epoch=?").run(recovery,epoch,confirmedAt,eventId,lease.epoch);this.database.prepare("DELETE FROM live_handoffs WHERE event_id=?").run(eventId);return {eventId,deviceInstallationId:recovery,epoch,confirmedAt,revoked:false};});}
  restart(){return new SqliteAuthorityCoordinator(this.database);}close(){this.database.close();}
}
