import { createHash } from "node:crypto";
import type { ArrangementPart, ArrangementVersion, PerformanceAssignment, Readiness } from "../../domain/src/arrangement.ts";
import { rankAvailability, validateSlot, validateTimeZone, type Availability, type RehearsalSlot } from "../../calendar/src/index.ts";
import { MemoryProviderAdapter, ProviderRateLimitError, type ProviderPort } from "../../providers/src/index.ts";
import type { DeliveryRecord } from "../../notifications/src/index.ts";

export class CoordinationError extends Error { readonly code:string;constructor(code:string){super(code);this.code=code;} }
type Command={communityId:string;eventId:string;actorId:string;roles:readonly string[];operationId:string;expectedRevision:number};
type Poll={id:string;communityId:string;eventId:string;revision:number;state:"open"|"closed";timeZone:string;slots:readonly RehearsalSlot[];requiredPersonIds:ReadonlySet<string>;responses:Map<string,Readonly<Record<string,Availability>>>};
type Session={id:string;communityId:string;eventId:string;pollId:string;slotId:string;agenda:readonly string[];revision:number;state:"published"|"cancelled";attendance:readonly string[];cancelReason?:string};
type Connection={id:string;communityId:string;kind:"calendar"|"notification";scopes:readonly string[];retention:"delete-on-disconnect";revision:number;revoked:boolean;callbacks:Set<string>};
const id=(prefix:string,value:string)=>`${prefix}_${createHash("sha256").update(value).digest("hex").slice(0,20)}`;
const allowedScopes=new Set(["free-busy:read","calendar-events:write","notifications:send"]);

export class CoordinationService {
  private arrangements=new Map<string,ArrangementVersion[]>(); private assignments=new Map<string,PerformanceAssignment>(); private polls=new Map<string,Poll>(); private sessions=new Map<string,Session>(); private connections=new Map<string,Connection>(); private deliveries=new Map<string,DeliveryRecord>();
  private provider:ProviderPort;
  constructor(options:{provider?:ProviderPort}={}){this.provider=options.provider??new MemoryProviderAdapter();}
  private authorize(command:Command){if(!command.communityId||!command.eventId||!command.actorId||!command.operationId||!command.roles.some(role=>role==="organizer"||role==="music-steward"||role==="performer"))throw new CoordinationError("denied");}
  private organizer(command:Command){this.authorize(command);if(!command.roles.some(role=>role==="organizer"||role==="music-steward"))throw new CoordinationError("denied");}
  private assertOwnPerformerAction(command:Command,performerId:string){if(command.roles.includes("performer")&&!command.roles.some(role=>role==="organizer"||role==="music-steward")&&command.actorId!==performerId)throw new CoordinationError("denied");}
  private scoped<T extends {communityId:string;eventId:string}>(command:Command,value:T){if(value.communityId!==command.communityId||value.eventId!==command.eventId)throw new CoordinationError("denied");}
  createArrangement(command:Command,input:{songId:string;key:string;notes:string;rightsState:ArrangementVersion["rightsState"];parts:readonly ArrangementPart[]}){this.organizer(command);if(command.expectedRevision!==0||!input.songId||!input.key||!input.parts.length||new Set(input.parts.map(p=>p.id)).size!==input.parts.length)throw new CoordinationError("invalid-arrangement");const arrangementId=id("decision",`${command.eventId}:${input.songId}`);if(this.arrangements.has(arrangementId))throw new CoordinationError("conflict");const value:ArrangementVersion={id:arrangementId,communityId:command.communityId,eventId:command.eventId,...input,revision:1,createdAt:new Date().toISOString()};this.arrangements.set(arrangementId,[value]);return value;}
  arrangement(arrangementId:string,revision?:number){const versions=this.arrangements.get(arrangementId);const value=revision?versions?.find(v=>v.revision===revision):versions?.at(-1);if(!value)throw new CoordinationError("not-found");return value;}
  reviseArrangement(command:Command,arrangementId:string,change:{key?:string;notes?:string;rightsState?:ArrangementVersion["rightsState"];parts?:readonly ArrangementPart[];affectedPartIds:readonly string[]}){this.organizer(command);const current=this.arrangement(arrangementId);this.scoped(command,current);if(current.revision!==command.expectedRevision)throw new CoordinationError("conflict");const next={...current,...change,revision:current.revision+1,createdAt:new Date().toISOString()};delete (next as Partial<typeof next>).affectedPartIds;this.arrangements.get(arrangementId)?.push(next);for(const assignment of this.assignments.values())if(assignment.decisionId===arrangementId&&!["withdrawn","declined","substituted"].includes(assignment.state)){assignment.decisionRevision=next.revision;if(change.affectedPartIds.includes(assignment.partId))assignment.readiness="learning";assignment.revision++;}return next;}
  volunteer(command:Command,input:{decisionId:string;partId:string;performerId:string;level:PerformanceAssignment["level"]}){this.authorize(command);this.assertOwnPerformerAction(command,input.performerId);const arrangement=this.arrangement(input.decisionId);this.scoped(command,arrangement);if(!arrangement.parts.some(p=>p.id===input.partId)||!input.performerId)throw new CoordinationError("invalid-assignment");const assignmentId=id("assignment",`${input.decisionId}:${input.partId}:${input.performerId}`);const old=this.assignments.get(assignmentId);if(old)return old;const value:PerformanceAssignment={id:assignmentId,communityId:command.communityId,eventId:command.eventId,decisionId:input.decisionId,decisionRevision:arrangement.revision,partId:input.partId,performerId:input.performerId,level:input.level,backup:input.level==="backup",state:"volunteered",readiness:"interested",revision:1};this.assignments.set(assignmentId,value);return value;}
  assignment(assignmentId:string){const value=this.assignments.get(assignmentId);if(!value)throw new CoordinationError("not-found");return value;}
  offer(command:Command,input:{decisionId:string;partId:string;performerId:string;backup?:boolean}){this.organizer(command);const value=this.assignment(id("assignment",`${input.decisionId}:${input.partId}:${input.performerId}`));this.scoped(command,value);if(value.revision!==command.expectedRevision||value.state!=="volunteered")throw new CoordinationError("conflict");value.state="offered";value.backup=input.backup??value.backup;value.revision++;return {...value};}
  respondToOffer(command:Command,input:{assignmentId:string;response:"accepted"|"declined"}){this.authorize(command);const value=this.assignment(input.assignmentId);this.scoped(command,value);this.assertOwnPerformerAction(command,value.performerId);if(value.revision!==command.expectedRevision||value.state!=="offered")throw new CoordinationError("conflict");value.state=input.response==="declined"?"declined":value.backup?"accepted":"assigned";value.revision++;return {...value};}
  setReadiness(command:Command,input:{assignmentId:string;state:Readiness}){this.authorize(command);const value=this.assignment(input.assignmentId);this.scoped(command,value);this.assertOwnPerformerAction(command,value.performerId);if(value.revision!==command.expectedRevision)throw new CoordinationError("conflict");value.readiness=input.state;value.revision++;return {...value};}
  withdraw(command:Command,assignmentId:string){this.authorize(command);const value=this.assignment(assignmentId);this.scoped(command,value);this.assertOwnPerformerAction(command,value.performerId);if(value.revision!==command.expectedRevision)throw new CoordinationError("conflict");const backup=[...this.assignments.values()].filter(candidate=>candidate.decisionId===value.decisionId&&candidate.partId===value.partId&&candidate.backup&&candidate.state==="accepted").sort((a,b)=>a.performerId.localeCompare(b.performerId))[0];if(backup){backup.state="assigned";backup.backup=false;backup.revision++;value.state="substituted";}else value.state="withdrawn";value.revision++;return {assignment:{...value},promotedAssignmentId:backup?.id??null};}
  createPoll(command:Command,input:{timeZone:string;slots:readonly RehearsalSlot[];requiredPersonIds:readonly string[]}){this.organizer(command);if(command.expectedRevision!==0||!input.slots.length)throw new CoordinationError("invalid-poll");try{validateTimeZone(input.timeZone);input.slots.forEach(validateSlot);}catch(error){throw new CoordinationError(error instanceof Error?error.message:"invalid-poll");}const pollId=id("poll",`${command.eventId}:${command.operationId}`),value:Poll={id:pollId,communityId:command.communityId,eventId:command.eventId,revision:1,state:"open",timeZone:input.timeZone,slots:input.slots,requiredPersonIds:new Set(input.requiredPersonIds),responses:new Map()};this.polls.set(pollId,value);return this.publicPoll(value);}
  private poll(pollId:string){const value=this.polls.get(pollId);if(!value)throw new CoordinationError("not-found");return value;}
  private publicPoll(value:Poll){return {...value,requiredPersonIds:[...value.requiredPersonIds],responses:undefined};}
  respondToPoll(command:Command,input:{pollId:string;personId:string;responses:Readonly<Record<string,Availability>>}){this.authorize(command);this.assertOwnPerformerAction(command,input.personId);const poll=this.poll(input.pollId);this.scoped(command,poll);if(poll.state!=="open")throw new CoordinationError("poll-closed");if(poll.revision!==command.expectedRevision||Object.keys(input.responses).some(slot=>!poll.slots.some(s=>s.id===slot)))throw new CoordinationError("conflict");poll.responses.set(input.personId,input.responses);poll.revision++;return this.publicPoll(poll);}
  rankPoll(pollId:string){const poll=this.poll(pollId);return rankAvailability(poll.slots,poll.responses,poll.requiredPersonIds);}
  closePoll(command:Command,pollId:string){this.organizer(command);return this.setPollState(command,pollId,"closed");}
  reopenPoll(command:Command,pollId:string){this.organizer(command);return this.setPollState(command,pollId,"open");}
  private setPollState(command:Command,pollId:string,state:Poll["state"]){const poll=this.poll(pollId);this.scoped(command,poll);if(poll.revision!==command.expectedRevision)throw new CoordinationError("conflict");poll.state=state;poll.revision++;return this.publicPoll(poll);}
  publishSession(command:Command,input:{pollId:string;slotId:string;agenda:readonly string[]}){this.organizer(command);const poll=this.poll(input.pollId);this.scoped(command,poll);if(poll.revision!==command.expectedRevision||!poll.slots.some(s=>s.id===input.slotId))throw new CoordinationError("conflict");const sessionId=id("rehearsal",`${input.pollId}:${input.slotId}`),value:Session={id:sessionId,communityId:command.communityId,eventId:command.eventId,pollId:input.pollId,slotId:input.slotId,agenda:input.agenda,revision:1,state:"published",attendance:[]};this.sessions.set(sessionId,value);return value;}
  private session(sessionId:string){const value=this.sessions.get(sessionId);if(!value)throw new CoordinationError("not-found");return value;}
  updateSession(command:Command,sessionId:string,input:{slotId?:string;agenda?:readonly string[]}){this.organizer(command);const value=this.session(sessionId);this.scoped(command,value);if(value.revision!==command.expectedRevision||value.state!=="published")throw new CoordinationError("conflict");Object.assign(value,input);value.revision++;return {...value};}
  recordOutcome(command:Command,sessionId:string,input:{attendance:readonly string[];readinessUpdates:readonly {assignmentId:string;state:Readiness}[]}){this.organizer(command);const value=this.session(sessionId);this.scoped(command,value);if(value.revision!==command.expectedRevision)throw new CoordinationError("conflict");value.attendance=input.attendance;for(const update of input.readinessUpdates){const assignment=this.assignment(update.assignmentId);if(assignment.eventId!==command.eventId)throw new CoordinationError("denied");assignment.readiness=update.state;assignment.revision++;}value.revision++;return {...value};}
  cancelSession(command:Command,sessionId:string,reason:string){this.organizer(command);const value=this.session(sessionId);this.scoped(command,value);if(value.revision!==command.expectedRevision||!reason)throw new CoordinationError("conflict");value.state="cancelled";value.cancelReason=reason;value.revision++;return {...value};}
  connectProvider(command:Command,input:{connectionId:string;kind:Connection["kind"];scopes:readonly string[];retention:Connection["retention"]}){this.organizer(command);if(command.expectedRevision!==0||input.scopes.some(scope=>!allowedScopes.has(scope)))throw new CoordinationError("scope-denied");const value:Connection={id:input.connectionId,communityId:command.communityId,kind:input.kind,scopes:input.scopes,retention:input.retention,revision:1,revoked:false,callbacks:new Set()};this.connections.set(value.id,value);return {id:value.id,kind:value.kind,scopes:value.scopes,retention:value.retention,revision:value.revision};}
  receiveProviderCallback(connectionId:string,callbackId:string,payload:unknown){const connection=this.connections.get(connectionId);if(!connection||connection.revoked)throw new CoordinationError("provider-revoked");if(!callbackId||JSON.stringify(payload).length>16_384)throw new CoordinationError("invalid-callback");if(connection.callbacks.has(callbackId))return "duplicate" as const;connection.callbacks.add(callbackId);return "accepted" as const;}
  async sendNotification(command:Command,input:{deliveryId:string;connectionId:string;category:string;recipientRef:string}){this.organizer(command);const connection=this.connections.get(input.connectionId);if(!connection||connection.revoked||connection.communityId!==command.communityId)throw new CoordinationError("provider-revoked");if(!connection.scopes.includes("notifications:send"))throw new CoordinationError("scope-denied");const hashValue=id("request",JSON.stringify(input));const old=this.deliveries.get(input.deliveryId);if(old){if(old.requestHash!==hashValue)throw new CoordinationError("replay-mismatch");if(old.state==="sent")return old;}const record:DeliveryRecord=old??{id:input.deliveryId,connectionId:input.connectionId,requestHash:hashValue,state:"pending",attempts:0};record.attempts++;this.deliveries.set(input.deliveryId,record);try{await this.provider.send(input.deliveryId,{category:input.category,recipientRef:input.recipientRef});record.state="sent";return record;}catch(error){if(error instanceof ProviderRateLimitError)throw new CoordinationError("rate-limited");throw new CoordinationError("provider-failed");}}
  disconnectProvider(command:Command,connectionId:string){this.organizer(command);const connection=this.connections.get(connectionId);if(!connection||connection.communityId!==command.communityId||connection.revision!==command.expectedRevision)throw new CoordinationError("conflict");connection.revoked=true;connection.callbacks.clear();connection.revision++;for(const record of this.deliveries.values())if(record.connectionId===connectionId&&record.state!=="sent")record.state="revoked";void this.provider.revoke(connectionId);return {id:connection.id,revoked:true,revision:connection.revision};}
}
